project:
  type: website

website:
  title: "Lily's DSPG 2024 Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lilychristenson
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



