project:
  type: website
  output-dir: docs

website:
  title: "Lily's DSPG 2024 Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lilychristenson
      - icon: linkedin
        href: https://www.linkedin.com/in/lily-christenson-080b51235/
format:
  html:
    theme: cosmo
    css: styles.css



